version: "3.7"

services:

  api:
    build: ./src
    image: api:latest
    volumes:
      - ./src/config:/home/node/config
      - ./src:/home/node/src
    ports:
      - "3001:3001"
    command: ./node_modules/.bin/nodemon src/index.js
    depends_on:
      - postgres

  postgres:
    image: postgres:12.1
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: {}

